// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GodotProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("GodotProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing GodotProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GodotProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "GodotProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing GodotProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
